#version: '3.8'

services:
  app:
    image: pisko0808/laravel:latest
    container_name: laravel
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    networks:
      - app-network
  web:
    image: pisko0808/nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
