apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravelapi.fullname" . }}-nginx-vhost
  labels:
    app: {{ include "laravelapi.fullname" . }}
    chart: {{ include "laravelapi.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  laravel.conf: |-
    server {
        listen {{ .Values.service.port }};
        listen [::]:{{ .Values.service.port }};

        server_name laravel.service.tst.consul;
        root /laravel/public;
        index index.php index.html index.htm;

        location / {
             try_files $uri /index.php?$args;
        }
        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        access_log /dev/stdout;
        error_log /dev/stderr;
    }