name: Docker
on:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.username }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run a simple shell command
        run: git clone https://github.com/joselfonseca/laravel-api.git
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Laravel image
        id: build-and-push-laravel
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.larave
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/laravel:latest

      - name: Build and push Nginx image
        id: build-and-push-nginx
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: Dockerfile.nginx
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest
  
      - name: Logout from Docker Hub
        run: docker logout