apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravelapi.fullname" . }}-nginx-vhost
  labels:
    app: {{ include "laravelapi.fullname" . }}
    chart: {{ include "laravelapi.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  laravel.conf: |-
       server {
           listen 80;
           index index.php index.html;
           server_name localhost;
       
           root /var/www/public;
       
           location / {
               try_files $uri $uri/ /index.php?$query_string;
           }
       
           location ~ \.php$ {
               include fastcgi_params;
               fastcgi_pass laravel:9000;
               fastcgi_index index.php;
               fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
           }
       
           location ~ /\.ht {
               deny all;
           }
       }
