apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravelapi.fullname" . }}-db
  labels:
    app: {{ include "laravelapi.fullname" . }}
    chart: {{ include "laravelapi.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  db-host: {{ .Values.database.host | b64enc | quote }}
  db-name: {{ .Values.database.name | b64enc | quote }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  db-user: {{ .Values.database.user | b64enc | quote }}
