apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravelapi.fullname" . }}
  labels:
    {{- include "laravelapi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravelapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravelapi.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: source-code
          emptyDir: {}
        - name: nginx-vhost
          configMap:
            name: {{ include "laravelapi.fullname" . }}-nginx-vhost
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravelapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        # Nginx Container
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.nginxService.image.repository }}:{{ .Values.nginxService.image.tag | default .Chart.AppVersion }}"
          #image: "nginx:alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginxService.internalPort }}
          volumeMounts:
            - name: nginx-vhost
              mountPath: /etc/nginx/conf.d
            - name: source-code
              mountPath: /var/www/
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: 9000
          volumeMounts:
            - name: source-code
              mountPath: /var/www/
          env:
          - name: DB_HOST
            value: mysql   
          - name: DB_DATABASE
            value: laravel
          - name: DB_USERNAME
            value: laravel
          - name: DB_PASSWORD
            value: laravel
          - name: DB_PORT
            value: "3306"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
