apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "laravel.fullname" . }}
  labels:
    app: {{ template "laravel.name" . }}
    chart: {{ template "laravel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "laravel.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "laravel.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: nginx-vhost
          configMap:
            name: {{ template "laravel.name" . }}-nginx-vhost
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "nginx:alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginxService.internalPort }}
          volumeMounts:
            - name: nginx-vhost
              mountPath: /etc/nginx/conf.d
        - name: {{ .Chart.Name }}
          image: "pisko0808/laravel:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-phpfpm
              containerPort: {{ .Values.phpfpmService.port }}
              protocol: TCP
          env:
          - name: DB_HOST
            value: mysql   
          - name: DB_HOST
            value: db
          - name: DB_DATABASE
            value: laravel
          - name: DB_USERNAME
            value: laravel
          - name: DB_PASSWORD
            value: laravel