name: Terraform Destroy
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  aws_region: eu-central-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan 
        run: terraform plan -out=tfplan
        working-directory: ./terraform
      - name: Terraform Destroy 
        run: terraform destroy -var-file="laravel.tfvars" --auto-approve
        working-directory: ./terraform