name: Terraform Apply

on:
  push:
    branches:
      - main
env:
  aws_region: eu-central-1
  TF_CLOUD_ORGANIZATION: personaldemo-space0001
  TF_WORKSPACE: demo   
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5\

      - name: Terraform Init
        run: terraform init 
        working-directory: ./terraform

      - name: Terraform Plan 
        run: terraform plan -out=tfplan -var-file="laravel.tfvars"
        working-directory: ./terraform

      - name: Terraform Apply 
        run: terraform apply -var-file="laravel.tfvars" --auto-approve 
        working-directory: ./terraform

  eks_deploy:
    uses: ./.github/workflows/build-deploy-eks.yml
    needs: terraform_apply
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  #terraform_destroy:
  #  uses: ./.github/workflows/terraform-destroy.yml
  #  needs: call-reusable-workflow
  #  secrets:
  #      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
